#!/usr/bin/env python3
import sys
import help
import error_handling
import generation_curve
import sum_result_n

def bombx():
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        help.help()
        sys.exit(0)
    if (error_handling.error_handling() == 84):
        sys.exit(84)
    if len(sys.argv) == 3:
        generation_curve.curve_generation()
    if (len(sys.argv) == 4):
        sum_result_n.sum_n()
    sys.exit(0)

bombx()
